Fix uWSGI installation error
Error message:
```
core/socket.c:713:28: error: use of undeclared identifier 'SOL_TCP'
                    if (setsockopt(serverfd, SOL_TCP, TCP_FASTOPEN, (const void *) &uwsgi.tcp_fast_open, sizeof(int)) < 0) {
```

* See changelog: https://github.com/unbit/uwsgi-docs
* On a Mac, compile issues could be caused due to libxml2:
  https://github.com/unbit/uwsgi/issues/1364#issuecomment-298144105